import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils/trpc';
import qrcode from 'qrcode';
import { useEffect, useState } from 'react';
import QRCanvas from '../components/QRCanvas';
import { getQrUrl } from '../utils/string';

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  const [qr, setQr] = useState<HTMLCanvasElement[]>([]);
  const hello = trpc.useQuery(['participants.getAll']);
  const data = [
    {
      id: 1,
      name: 'kangguru',
    },
    {
      id: 2,
      name: 'hiu',
    },
    {
      id: 3,
      name: 'ayam',
    },
    {
      id: 4,
      name: 'unta',
    },
  ];

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container mx-auto flex flex-col items-center justify-center h-screen p-4'>
        {data.map((val) => (
          <div key={val.id}>{val.name}</div>
        ))}
      </main>
    </>
  );
};

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className='flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105'>
      <h2 className='text-lg text-gray-700'>{name}</h2>
      <p className='text-sm text-gray-600'>{description}</p>
      <a
        className='mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2'
        href={documentation}
        target='_blank'
        rel='noreferrer'
      >
        Documentation
      </a>
    </section>
  );
};

export default Home;
